[package]
name = "wormhole"
version = "0.1.0"
edition = "2021"

[dependencies]
event-listener = {version = "2.5"}
thiserror = "1.0"

[features]


[dev-dependencies]
tokio = { version = "1", features = ["full"] }
chrono = "0.4"
log = "0.4"
crossbeam-channel = "0.5"
kanal = "0.1.0-pre7"