[package]
name = "wormhole"
version = "0.1.0"
edition = "2021"

[dependencies]
event-listener = {version = "2.5", optional = true }

[features]
async = ["event-listener"]


[dev-dependencies]
tokio = { version = "1", features = ["full"] }