[package]
name = "gemino"
version = "0.1.0"
edition = "2021"

[dependencies]
event-listener = {version = "2.5"}
thiserror = "1.0"

[features]

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
tokio-test = "0.4"
chrono = "0.4"
log = "0.4"
